agent_id: dns_agent
agent_type: ml_based
analysis_rules:
  analysis_interval: 120
  feature_extraction:
    domain_patterns: true
    query_count: true
    query_types: true
    response_time: true
  lookback_minutes: 10
  severity_mapping:
    dns_amplification: 5
    query_flood: 4
    suspicious_domain: 3
  thresholds:
    amplification_ratio_threshold: 10
    query_flood_threshold: 1000
    response_time_threshold: 5000
capabilities:
- DNS amplification detection
- Query flood detection
- Suspicious domain detection
description: DNS query anomaly detection
model_path: /home/dannguyen/mcp_service/backend/models/model_tmp0w_c3mb2.zip
name: DNSAgent
process_filters:
- named
- dnsmasq
- systemd-resolved
- dnsmasq-dhcp
