agent_id: system_agent
agent_type: ml_based
analysis_rules:
  analysis_interval: 300
  feature_extraction:
    cpu_usage: true
    disk_io: true
    failed_logins: true
    memory_usage: true
    network_connections: true
  lookback_minutes: 15
  severity_mapping:
    auth_failure: 3
    process_anomaly: 5
    resource_anomaly: 4
  thresholds:
    cpu_threshold: 90
    failed_login_threshold: 5
    memory_threshold: 85
capabilities:
- System resource anomaly detection
- Authentication failure detection
- Process behavior analysis
description: System-level anomaly detection
model_path: /home/dannguyen/WNC/mcp_service/backend/models/model_tmpjgzrlhlg.zip
name: SystemAgent
process_filters:
- systemd
- cron
- sshd
- sudo
- watchdog
