agent_id: wifi_agent
agent_type: ml_based
analysis_rules:
  analysis_interval: 60
  lookback_minutes: 5
  severity_mapping: {}
capabilities:
- Authentication failure detection
- Deauthentication flood detection
- Beacon frame flood detection
description: WiFi anomaly detection agent
model_path: /home/dannguyen/mcp_service/backend/models/model_tmpo3jl9ugx.zip
name: WiFiAgent
process_filters:
- hostapd
- wlceventd
- acsd
