version: '2.0.0'
model:
  type: isolation_forest
  n_estimators: 100
  max_samples: auto
  contamination: 0.1
  random_state: 42
features:
  numeric:
    - signal_strength
    - connection_time
    - packet_loss
  categorical:
    - device_type
    - connection_type
  temporal:
    - hour_of_day
    - day_of_week
training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  n_jobs: -1
storage:
  directory: models
  version_format: '%Y%m%d_%H%M%S'
  keep_last_n_versions: 5
  backup_enabled: true
  compression: true
  retention_days: 30
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  thresholds:
    accuracy: 0.8
    precision: 0.7
    recall: 0.7
    f1_score: 0.7
integration:
  training_service_path: /home/dannguyen/WNC/mcp_training
  auto_import: false
  import_interval: 3600
  validate_imports: true
monitoring:
  enable_drift_detection: true
  drift_threshold: 0.1
  performance_tracking: true
  resource_monitoring: true
  model_health_checks: true
  alerting:
    enabled: true
    email_notifications: false
    slack_notifications: false
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/model_inference.log
  rotation:
    max_size: 100MB
    backup_count: 10