# Data Source Configuration

host: 192.168.10.14
port: 5432
database: netmonitor_db
user: netmonitor_user
password: netmonitor_password

# Query Configuration
query:
  batch_size: 1000
  timeout: 30

# Data Validation
validation:
  required_tables:
    - name: log_entries
      data_types:
        timestamp: "timestamp without time zone"
        device_id: "character varying"
        message: "text"
        raw_message: "text"
      indexes:
        - "log_entries_timestamp_idx"
        - "log_entries_device_id_idx"

  optional_tables:
    - name: anomaly_records
      data_types:
        timestamp: "timestamp without time zone"
        device_id: "character varying"
        anomaly_type: "character varying"
        severity: "integer"
        details: "jsonb"
      indexes:
        - "anomaly_records_timestamp_idx"
        - "anomaly_records_device_id_idx"

    - name: anomaly_patterns
      data_types:
        pattern_id: "character varying"
        pattern_type: "character varying"
        description: "text"
        created_at: "timestamp without time zone"
      indexes:
        - "anomaly_patterns_pattern_id_idx"

# Performance Thresholds
performance:
  max_query_time: 5.0  # seconds
  min_rows_per_second: 1000 