# Model training configuration

# Model parameters
model:
  type: isolation_forest
  n_estimators: 100
  max_samples: auto
  contamination: 0.1
  random_state: 42

# Feature engineering
features:
  numeric:
    - signal_strength
    - channel
    - data_rate
    - packet_loss_rate
    - retry_rate
  categorical:
    - device_type
    - connection_type
  temporal:
    - hour_of_day
    - day_of_week
    - is_weekend

# Training parameters
training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  n_jobs: -1

# Model storage
storage:
  directory: models
  version_format: "%Y%m%d_%H%M%S"
  keep_last_n_versions: 5

# Evaluation metrics
evaluation:
  metrics:
    - average_precision
    - precision_recall_curve
  thresholds:
    precision: 0.8
    recall: 0.8

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/model_training.log 