# Server Configuration

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 60
  keep_alive: 5

model:
  model_dir: "models"
  default_version: "latest"
  cache_size: 1000

monitoring:
  drift_threshold: 0.1
  window_size: 1000
  metrics_interval: 60

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/model_server.log"
  max_size: 10485760  # 10MB
  backup_count: 5

security:
  cors_origins:
    - "http://localhost:3000"
  rate_limit:
    requests_per_minute: 100
    burst_limit: 150
  authentication:
    enabled: true
    api_key_header: "X-API-Key"

prometheus:
  enabled: true
  metrics_path: "/metrics"
  scrape_interval: 15 