# Server configuration

# Server settings
server:
  host: 0.0.0.0
  port: 8000
  workers: 4
  reload: false
  timeout: 60
  keep_alive: 5

# Model settings
model:
  model_dir: models
  default_version: latest
  load_on_startup: true
  cache_size: 1000
  batch_size: 32

# Monitoring settings
monitoring:
  drift_threshold: 0.1
  window_size: 1000
  metrics_interval: 60
  alert_threshold: 0.2

# Logging settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/model_server.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Security settings
security:
  cors_origins:
    - "*"
  rate_limit:
    requests_per_minute: 100
  authentication:
    enabled: false
    token_expiry: 3600

# Database settings
database:
  host: localhost
  port: 5432
  name: mcp_service
  user: mcp_service
  password: ${DB_PASSWORD}
  pool_size: 20
  max_overflow: 10

# Redis settings
redis:
  host: localhost
  port: 6379
  db: 0
  password: ${REDIS_PASSWORD}
  max_connections: 100

# Prometheus settings
prometheus:
  enabled: true
  path: /metrics
  port: 9090 